inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  Exclude:
    - "www/bin/**/*"
    - "www/db/**/*"
    - "www/config/**/*"
    - "www/lib/tasks/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/MultilineMethodCallIndentation:
  Enabled: false

Style/Documentation:
  Enabled: false
