inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "db/**/*"
    - "shared/db/**/*"
    - "config/**/*"
    - "lib/tasks/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/MultilineMethodCallIndentation:
  Enabled: false

Style/Documentation:
  Enabled: false
