default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 20 } %>

development:
  <<: *default
  database: collectif_objets_dev

test:
  <<: *default
  database: collectif_objets_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
