test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

scaleway: &scaleway
  service: S3
  endpoint: https://s3.fr-par.scw.cloud
  region: fr-par

scaleway_production:
  <<: *scaleway
  access_key_id: <%= Rails.application.credentials.dig(:scaleway, :project_default, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:scaleway, :project_default, :secret_access_key) %>
  bucket: collectif-objets-production

scaleway_staging:
  <<: *scaleway
  access_key_id: <%= Rails.application.credentials.dig(:scaleway, :project_co, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:scaleway, :project_co, :secret_access_key) %>
  bucket: collectif-objets-staging2

scaleway_development:
  <<: *scaleway
  access_key_id: <%= Rails.application.credentials.dig(:scaleway, :project_co, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:scaleway, :project_co, :secret_access_key) %>
  bucket: collectif-objets-development2
