name: "CI"

defaults:
  run:
    working-directory: ./www

on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: ./www
      - name: Set up database schema
        run: bin/rails db:schema:load
      - name: Run tests
        run: bundle exec rspec

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: ./www
#       - name: Security audit dependencies
#         run: bin/bundler-audit --update
#       - name: Security audit application code
#         run: bin/brakeman -q -w2
      - name: Lint Ruby files
        run: bundle exec rubocop --parallel

  deploy:
    runs-on: ubuntu-latest
    needs: test
    # if: github.ref == 'refs/heads/main'
    env:
      SCALINGO_TOKEN: ${{ secrets.SCALINGO_TOKEN }}
    steps:
      - name: Install Scalingo CLI
        run: curl -O https://cli-dl.scalingo.com/install && bash install
      - name: Scalingo login api token
        run: scalingo login --api-token $SCALINGO_TOKEN
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy www to staging
        run: ./deploy_script.sh www staging
